name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          uuid-dev \
          zlib1g-dev \
          meson \
          libsystemd-dev \
          libdaxctl-dev \
          libkmod-dev \
          libjson-c-dev \
          libtraceevent-dev \
          libtracefs-dev \
          asciidoctor \
          libudev-dev \
          libkeyutils-dev \
          libiniparser-dev \
          libcurl4-openssl-dev\
          pkg-config
    - name: make
      run: make all
    - name: make test
      run: make test

